name: PR Java Code Review with ChatGPT

on:
  pull_request:


    types:
      - opened
      - synchronize
      - reopened

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '21'          # Updated to Java 21
          distribution: 'temurin'     # Using the Temurin distribution

      - name: Install dependencies
        run: mvn clean install

      - name: Extract Java files from PR
        run: |
          git diff --name-only origin/master...HEAD | grep '.java$' > java_files.txt
          cat java_files.txt

      - name: Review Java code with ChatGPT
        run: |
          PR_CODE=""
          while read -r file; do
            PR_CODE+=$(cat $file)
            PR_CODE+=$'\n\n'
          done < java_files.txt

          RESPONSE=$(curl -X POST https://api.openai.com/v1/completions \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "text-davinci-003",
              "prompt": "Review the following Java code and provide
